Parameters:

  Domain:
    Type: String
  Application:
    Type: String

Outputs:

  HostedZoneId:
    Value: !Ref HostedZone

Resources:

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name:
        Ref: Domain
      HostedZoneTags:
        - Key: "Application"
          Value: !Ref Application
