AWSTemplateFormatVersion: "2010-09-09"

Parameters:

  Domain:
    Type: String
  Application:
    Type: String

Outputs:

  HostedZoneId:
    Description: The ID of the Hosted Zone in Route 53
    Value: !Ref HostedZone

Resources:

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name:
        Ref: Domain
      HostedZoneTags:
        - Key: "Application"
          Value: !Ref Application
