AWSTemplateFormatVersion: "2010-09-09"

Parameters:

  Domain:
    Type: String

Resources:

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name:
        Ref: Domain

Outputs:

  HostedZoneId:
    Description: The ID of the Hosted Zone in Route 53
    Value:
      Ref: HostedZone
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-HostedZoneId
