AWSTemplateFormatVersion: '2010-09-09'
Description: A template for creating a CodeBuild project for building projects from GitHub
Parameters:
  ArtifactsBucket:
    Type: String
    Description: The S3 bucket into which build artifacts are be stored
  ProjectName:
    Type: String
    Description: The name of the CodeBuild project
  RepositoryURL:
    Type: String
    Description: The HTTPS clone URL to the repository at GitHub

Resources:

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      Source:
        Type: GITHUB
        Location: !Ref RepositoryURL
      Artifacts:
        Type: S3
        Location: !Ref ArtifactsBucket
      Triggers:
        Webhook: true
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildTrustPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub
                    - arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}
                    - { ProjectName: !Ref ProjectName }
                  - !Sub
                    - arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}:*
                    - { ProjectName: !Ref ProjectName }
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource:
                  - !Sub
                    - arn:aws:s3:::${ArtifactsBucket}/*
                    - { ArtifactsBucket: !Ref ArtifactsBucket}
